/*
 * Debug.h
 *
 *  Created on: 2016. 8. 17.
 *      Author: jhkim
 */

#ifndef DEBUG_H_
#define DEBUG_H_

#include <cstdint>

#include "../common.h"
#include "../activation/Activation.h"
#include "../dataset/DataSet.h"
#include "../dataset/ImagePackDataSet.h"
#include "../dataset/MockDataSet.h"
#include "../layer/ConvLayer.h"
#include "../layer/DepthConcatLayer.h"
#include "../layer/FullyConnectedLayer.h"
#include "../layer/InputLayer.h"
#include "../layer/LayerConfig.h"
#include "../layer/LRNLayer.h"
#include "../layer/PoolingLayer.h"
#include "../layer/SoftmaxLayer.h"
#include "../layer/SplitLayer.h"
#include "../network/NetworkConfig.h"
#include "../pooling/Pooling.h"

template <typename Dtype> class DataSet;
template <typename Dtype> class LayersConfig;







template <typename Dtype>
DataSet<Dtype>* createMnistDataSet() {
	DataSet<Dtype>* dataSet = new ImagePackDataSet<Dtype>(
			"/data/train_pack/mnist/train_data",
			"/data/train_pack/mnist/train_label",
			1,
			"/data/train_pack/mnist/test_data",
			"/data/train_pack/mnist/test_label",
			1);
	dataSet->setMean({0.13066047740});
	return dataSet;

}

template <typename Dtype>
DataSet<Dtype>* createMockDataSet() {
	DataSet<Dtype>* dataSet = new MockDataSet<Dtype>(
			224,
			224,
			3,
			10,
			10,
			1000);
	dataSet->setMean({0.0, 0.0, 0.0});
	return dataSet;
}

template <typename Dtype>
DataSet<Dtype>* createSampleDataSet() {
	DataSet<Dtype>* dataSet = new ImagePackDataSet<Dtype>(
			"/data/train_pack/ILSVRC2012/save/sample/train_data",
			"/data/train_pack/ILSVRC2012/save/sample/train_label",
			3,
			"/data/train_pack/ILSVRC2012/save/sample/train_data",
			"/data/train_pack/ILSVRC2012/save/sample/train_label",
			1);
	dataSet->setMean({0.0, 0.0, 0.0});
	return dataSet;
}

template <typename Dtype>
DataSet<Dtype>* createImageNet1000DataSet() {
	DataSet<Dtype>* dataSet = new ImagePackDataSet<Dtype>(
			"/data/train_pack/ILSVRC2012/save/1000/train_data",
			"/data/train_pack/ILSVRC2012/save/1000/train_label",
			1,
			"/data/train_pack/ILSVRC2012/save/1000/test_data",
			"/data/train_pack/ILSVRC2012/save/1000/test_label",
			1);
	dataSet->setMean({0.47684615850, 0.45469805598, 0.41394191980});
	return dataSet;
}

template <typename Dtype>
DataSet<Dtype>* createImageNet10000DataSet() {
	DataSet<Dtype>* dataSet = new ImagePackDataSet<Dtype>(
			"/data/train_pack/ILSVRC2012/save/10000/train_data",
			"/data/train_pack/ILSVRC2012/save/10000/train_label",
			40,
			"/data/train_pack/ILSVRC2012/save/10000/test_data",
			"/data/train_pack/ILSVRC2012/save/10000/test_label",
			1);
	dataSet->setMean({0.47684615850, 0.45469805598, 0.41394191980});
	return dataSet;
}

template <typename Dtype>
DataSet<Dtype>* createImageNet50000DataSet() {
	DataSet<Dtype>* dataSet = new ImagePackDataSet<Dtype>(
			"/data/train_pack/ILSVRC2012/save/50000/train_data",
			"/data/train_pack/ILSVRC2012/save/50000/train_label",
			1,
			"/data/train_pack/ILSVRC2012/save/50000/test_data",
			"/data/train_pack/ILSVRC2012/save/50000/test_label",
			1);
	dataSet->setMean({0.47684615850, 0.45469805598, 0.41394191980});
	return dataSet;
}





template <typename Dtype>
LayersConfig<Dtype>* createCNNSimpleLayersConfig() {
	LayersConfig<Dtype>* layersConfig =
			(new typename LayersConfig<Dtype>::Builder())
			->layer((new typename InputLayer<Dtype>::Builder())
					->id(0)
					->name("inputLayer")
					->outputs({"data", "label"})
					->source("/data/train_pack/mnist")
					->sourceType("ImagePack")
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(1)
					->name("convLayer1")
					->filterDim(3, 3, 1, 2, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, 0.2)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({0})
					//->nextLayerIndices({2})
					->inputs({"data"})
					->outputs({"conv1/3x3_s2"}))
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(2)
					->name("poolingLayer1")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					//->prevLayerIndices({1})
					//->nextLayerIndices({3})
					->inputs({"conv1/3x3_s2"})
					->outputs({"pool1/3x3_s1"}))
			->layer((new typename SoftmaxLayer<Dtype>::Builder())
					->id(3)
					->name("softmaxLayer")
					->nOut(10)
					->pDropout(0.4)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, 0.0)
					//->prevLayerIndices({2})
					->inputs({"pool1/3x3_s1", "label"})
					->outputs({"prob"}))
			->build();

	return layersConfig;
}


template <typename Dtype>
LayersConfig<Dtype>* createCNNDoubleLayersConfig() {
	const float bias_const = 0.2;

	LayersConfig<Dtype>* layersConfig =
			(new typename LayersConfig<Dtype>::Builder())
			->layer((new typename InputLayer<Dtype>::Builder())
					->id(0)
					->name("inputLayer")
					//->nextLayerIndices({1})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(1)
					->name("convLayer1")
					->filterDim(5, 5, 1, 20, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({0})
					//->nextLayerIndices({2})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(2)
					->name("poolingLayer1")
					->poolDim(3, 3, 2)
					->poolingType(Pooling<Dtype>::Max)
					//->prevLayerIndices({1})
					//->nextLayerIndices({3})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(3)
					->name("convLayer2")
					->filterDim(5, 5, 20, 40, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({2})
					//->nextLayerIndices({4})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(4)
					->name("poolingLayer2")
					->poolDim(3, 3, 2)
					->poolingType(Pooling<Dtype>::Max)
					//->prevLayerIndices({3})
					//->nextLayerIndices({5})
					)
			->layer((new typename FullyConnectedLayer<Dtype>::Builder())
					->id(5)
					->name("fullyConnectedLayer1")
					->nOut(100)
					->pDropout(0.4)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::Type::ReLU)
					//->prevLayerIndices({4})
					//->nextLayerIndices({6})
					)
			->layer((new typename SoftmaxLayer<Dtype>::Builder())
					->id(6)
					->name("softmaxLayer")
					->nOut(10)
					->pDropout(0.4)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, 0.0)
					//->prevLayerIndices({5})
					)
			->build();

	return layersConfig;
}



template <typename Dtype>
LayersConfig<Dtype>* createGoogLeNetInception5BLayersConfig() {
	const float bias_const = 0.1;

    std::cout << std::endl;
	LayersConfig<Dtype>* layersConfig =
			(new typename LayersConfig<Dtype>::Builder())
			->layer((new typename InputLayer<Dtype>::Builder())
					->id(0)
					->name("input")
					->outputs({"data", "label"})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(1)
					->name("conv1/7x7_s2")
					->filterDim(7, 7, 3, 64, 2)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"data"})
					->outputs({"conv1/7x7_s2"})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(2)
					->name("pool1/3x3_s2")
					->poolDim(3, 3, 2)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"conv1/7x7_s2"})
					->outputs({"pool1/3x3_s2"})
					)
			->layer((new typename LRNLayer<Dtype>::Builder())
					->id(3)
					->name("pool1/norm1")
					->lrnDim(5, 0.0001, 0.75, 2.0)
					->inputs({"pool1/3x3_s2"})
					->outputs({"pool1/norm1"})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(4)
					->name("conv2/3x3_reduce")
					->filterDim(1, 1, 64, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool1/norm1"})
					->outputs({"conv2/3x3_reduce"})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(5)
					->name("conv2/3x3")
					->filterDim(3, 3, 64, 192, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"conv2/3x3_reduce"})
					->outputs({"conv2/3x3"})
					)
			->layer((new typename LRNLayer<Dtype>::Builder())
					->id(6)
					->name("conv2/norm2")
					->lrnDim(5, 0.0001, 0.75, 2.0)
					->inputs({"conv2/3x3"})
					->outputs({"conv2/norm2"})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(7)
					->name("pool2/3x3_s2")
					->poolDim(3, 3, 2)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"conv2/norm2"})
					->outputs({"pool2/3x3_s2"})
					)
					/*
			->layer((new typename SplitLayer<Dtype>::Builder())
					->id()
					->name("split2")
					->inputs({"pool2/3x3_s2"})
					->outputs({"pool2/3x3_s2_0", "pool2/3x3_s2_1", "pool2/3x3_s2_2", "pool2/3x3_s2_3"})
					)
					*/
			//INCEPTION 3A
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(8)
					->name("inception_3a/1x1")
					->filterDim(1, 1, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool2/3x3_s2"})
					->outputs({"inception_3a/1x1"})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(9)
					->name("inception_3a/3x3_reduce")
					->filterDim(1, 1, 192, 96, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool2/3x3_s2"})
					->outputs({"inception_3a/3x3_reduce"})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(10)
					->name("inception_3a/3x3")
					->filterDim(3, 3, 96, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3a/3x3_reduce"})
					->outputs({"inception_3a/3x3"})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(11)
					->name("inception_3a/5x5_reduce")
					->filterDim(3, 3, 192, 16, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool2/3x3_s2"})
					->outputs({"inception_3a/5x5_reduce"})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(12)
					->name("inception_3a/5x5")
					->filterDim(3, 3, 16, 32, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3a/5x5_reduce"})
					->outputs({"inception_3a/5x5"})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(13)
					->name("inception_3a/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"pool2/3x3_s2"})
					->outputs({"inception_3a/pool"})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(14)
					->name("inception_3a/pool_proj")
					->filterDim(1, 1, 192, 32, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3a/pool"})
					->outputs({"inception_3a/pool_proj"})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(15)
					->name("inception_3a/output")
					->inputs({"inception_3a/1x1", "inception_3a/3x3",
								"inception_3a/5x5", "inception_3a/pool_proj"})
					->outputs({"inception_3a/output"})
					)
			//INCEPTION 3B
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(16)
					->name("inception_3b/1x1")
					->filterDim(1, 1, 256, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3a/output"})
					->outputs({"inception_3b/1x1"})
					//->prevLayerIndices({15})
					//->nextLayerIndices({23})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(17)
					->name("inception_3b/3x3_reduce")
					->filterDim(1, 1, 256, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3a/output"})
					->outputs({"inception_3b/3x3_reduce"})
					//->prevLayerIndices({15})
					//->nextLayerIndices({18})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(18)
					->name("inception_3b/3x3")
					->filterDim(3, 3, 128, 192, 1)
					//->filterDim(3, 3, 96, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3b/3x3_reduce"})
					->outputs({"inception_3b/3x3"})
					//->prevLayerIndices({17})
					//->nextLayerIndices({23})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(19)
					->name("inception_3b/5x5_reduce")
					->filterDim(3, 3, 256, 32, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3a/output"})
					->outputs({"inception_3b/5x5_reduce"})
					//->prevLayerIndices({15})
					//->nextLayerIndices({20})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(20)
					->name("inception_3b/5x5")
					->filterDim(3, 3, 32, 96, 1)
					//->filterDim(3, 3, 16, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3b/5x5_reduce"})
					->outputs({"inception_3b/5x5"})
					//->prevLayerIndices({19})
					//->nextLayerIndices({23})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(21)
					->name("inception_3b/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"inception_3a/output"})
					->outputs({"inception_3b/pool"})
					//->prevLayerIndices({15})
					//->nextLayerIndices({22})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(22)
					->name("inception_3b/pool_proj")
					->filterDim(1, 1, 256, 64, 1)
					//->filterDim(3, 3, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_3b/pool"})
					->outputs({"inception_3b/pool_proj"})
					//->prevLayerIndices({21})
					//->nextLayerIndices({23})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(23)
					->name("inception_3b/output")
					->inputs({"inception_3b/1x1", "inception_3b/3x3",
								"inception_3b/5x5", "inception_3b/pool_proj"})
					->outputs({"inception_3b/output"})
					//->prevLayerIndices({16, 18, 20, 22})
					//->nextLayerIndices({24})
					)


			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(24)
					->name("pool3/3x3_s2")
					->poolDim(3, 3, 2)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"inception_3b/output"})
					->outputs({"pool3/3x3_s2"})
					//->prevLayerIndices({23})
					//->nextLayerIndices({25, 26, 28, 30})
					)

			//INCEPTION 4A
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(25)
					->name("inception_4a/1x1")
					->filterDim(1, 1, 480, 192, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool3/3x3_s2"})
					->outputs({"inception_4a/1x1"})
					//->prevLayerIndices({24})
					//->nextLayerIndices({32})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(26)
					->name("inception_4a/3x3_reduce")
					->filterDim(1, 1, 480, 96, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool3/3x3_s2"})
					->outputs({"inception_4a/3x3_reduce"})
					//->prevLayerIndices({24})
					//->nextLayerIndices({27})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(27)
					->name("inception_4a/3x3")
					->filterDim(3, 3, 96, 208, 1)
					//->filterDim(3, 3, 96, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4a/3x3_reduce"})
					->outputs({"inception_4a/3x3"})
					//->prevLayerIndices({26})
					//->nextLayerIndices({32})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(28)
					->name("inception_4a/5x5_reduce")
					->filterDim(3, 3, 480, 16, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool3/3x3_s2"})
					->outputs({"inception_4a/5x5_reduce"})
					//->prevLayerIndices({24})
					//->nextLayerIndices({29})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(29)
					->name("inception_4a/5x5")
					->filterDim(3, 3, 16, 48, 1)
					//->filterDim(3, 3, 16, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4a/5x5_reduce"})
					->outputs({"inception_4a/5x5"})
					//->prevLayerIndices({28})
					//->nextLayerIndices({32})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(30)
					->name("inception_4a/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"pool3/3x3_s2"})
					->outputs({"inception_4a/pool"})
					//->prevLayerIndices({24})
					//->nextLayerIndices({31})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(31)
					->name("inception_4a/pool_proj")
					->filterDim(1, 1, 480, 64, 1)
					//->filterDim(3, 3, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4a/pool"})
					->outputs({"inception_4a/pool_proj"})
					//->prevLayerIndices({30})
					//->nextLayerIndices({32})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(32)
					->name("inception_4a/output")
					->inputs({"inception_4a/1x1", "inception_4a/3x3",
								"inception_4a/5x5", "inception_4a/pool_proj"})
					->outputs({"inception_4a/output"})
					//->prevLayerIndices({25, 27, 29, 31})
					//->nextLayerIndices({33, 34, 36, 38})
					)



			//INCEPTION 4B
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(33)
					->name("inception_4b/1x1")
					->filterDim(1, 1, 512, 160, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4a/output"})
					->outputs({"inception_4b/1x1"})
					//->prevLayerIndices({32})
					//->nextLayerIndices({40})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(34)
					->name("inception_4b/3x3_reduce")
					->filterDim(1, 1, 512, 112, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4a/output"})
					->outputs({"inception_4b/3x3_reduce"})
					//->prevLayerIndices({32})
					//->nextLayerIndices({35})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(35)
					->name("inception_4b/3x3")
					->filterDim(3, 3, 112, 224, 1)
					//->filterDim(3, 3, 96, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4b/3x3_reduce"})
					->outputs({"inception_4b/3x3"})
					//->prevLayerIndices({34})
					//->nextLayerIndices({40})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(36)
					->name("inception_4b/5x5_reduce")
					->filterDim(3, 3, 512, 24, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4a/output"})
					->outputs({"inception_4b/5x5_reduce"})
					//->prevLayerIndices({32})
					//->nextLayerIndices({37})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(37)
					->name("inception_4b/5x5")
					->filterDim(3, 3, 24, 64, 1)
					//->filterDim(3, 3, 16, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4b/5x5_reduce"})
					->outputs({"inception_4b/5x5"})
					//->prevLayerIndices({36})
					//->nextLayerIndices({40})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(38)
					->name("inception_4b/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"inception_4a/output"})
					->outputs({"inception_4b/pool"})
					//->prevLayerIndices({32})
					//->nextLayerIndices({39})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(39)
					->name("inception_4b/pool_proj")
					->filterDim(1, 1, 512, 64, 1)
					//->filterDim(3, 3, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4b/pool"})
					->outputs({"inception_4b/pool_proj"})
					//->prevLayerIndices({38})
					//->nextLayerIndices({40})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(40)
					->name("inception_4b/output")
					->inputs({"inception_4b/1x1", "inception_4b/3x3",
								"inception_4b/5x5", "inception_4b/pool_proj"})
					->outputs({"inception_4b/output"})
					//->prevLayerIndices({33, 35, 37, 39})
					//->nextLayerIndices({41, 42, 44, 46})
					)



			//INCEPTION 4C
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(41)
					->name("inception_4c/1x1")
					->filterDim(1, 1, 512, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4b/output"})
					->outputs({"inception_4c/1x1"})
					//->prevLayerIndices({40})
					//->nextLayerIndices({48})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(42)
					->name("inception_4c/3x3_reduce")
					->filterDim(1, 1, 512, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4b/output"})
					->outputs({"inception_4c/3x3_reduce"})
					//->prevLayerIndices({40})
					//->nextLayerIndices({43})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(43)
					->name("inception_4c/3x3")
					->filterDim(3, 3, 128, 256, 1)
					//->filterDim(3, 3, 96, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4c/3x3_reduce"})
					->outputs({"inception_4c/3x3"})
					//->prevLayerIndices({42})
					//->nextLayerIndices({48})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(44)
					->name("inception_4c/5x5_reduce")
					->filterDim(3, 3, 512, 24, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4b/output"})
					->outputs({"inception_4c/5x5_reduce"})
					//->prevLayerIndices({40})
					//->nextLayerIndices({45})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(45)
					->name("inception_4c/5x5")
					->filterDim(3, 3, 24, 64, 1)
					//->filterDim(3, 3, 16, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4c/5x5_reduce"})
					->outputs({"inception_4c/5x5"})
					//->prevLayerIndices({44})
					//->nextLayerIndices({48})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(46)
					->name("inception_4c/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"inception_4b/output"})
					->outputs({"inception_4c/pool"})
					//->prevLayerIndices({40})
					//->nextLayerIndices({47})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(47)
					->name("inception_4c/pool_proj")
					->filterDim(1, 1, 512, 64, 1)
					//->filterDim(3, 3, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4c/pool"})
					->outputs({"inception_4c/pool_proj"})
					//->prevLayerIndices({46})
					//->nextLayerIndices({48})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(48)
					->name("inception_4c/output")
					->inputs({"inception_4c/1x1", "inception_4c/3x3",
								"inception_4c/5x5", "inception_4c/pool_proj"})
					->outputs({"inception_4c/output"})
					//->prevLayerIndices({41, 43, 45, 47})
					//->nextLayerIndices({49, 50, 52, 54})
					)




			//INCEPTION 4D
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(49)
					->name("inception_4d/1x1")
					->filterDim(1, 1, 512, 112, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4c/output"})
					->outputs({"inception_4d/1x1"})
					//->prevLayerIndices({48})
					//->nextLayerIndices({56})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(50)
					->name("inception_4d/3x3_reduce")
					->filterDim(1, 1, 512, 144, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4c/output"})
					->outputs({"inception_4d/3x3_reduce"})
					//->prevLayerIndices({48})
					//->nextLayerIndices({51})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(51)
					->name("inception_4d/3x3")
					->filterDim(3, 3, 144, 288, 1)
					//->filterDim(3, 3, 96, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4d/3x3_reduce"})
					->outputs({"inception_4d/3x3"})
					//->prevLayerIndices({50})
					//->nextLayerIndices({56})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(52)
					->name("inception_4d/5x5_reduce")
					->filterDim(3, 3, 512, 32, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4c/output"})
					->outputs({"inception_4d/5x5_reduce"})
					//->prevLayerIndices({48})
					//->nextLayerIndices({53})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(53)
					->name("inception_4d/5x5")
					->filterDim(3, 3, 32, 64, 1)
					//->filterDim(3, 3, 16, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4d/5x5_reduce"})
					->outputs({"inception_4d/5x5"})
					//->prevLayerIndices({52})
					//->nextLayerIndices({56})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(54)
					->name("inception_4d/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"inception_4c/output"})
					->outputs({"inception_4d/pool"})
					//->prevLayerIndices({48})
					//->nextLayerIndices({55})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(55)
					->name("inception_4d/pool_proj")
					->filterDim(1, 1, 512, 64, 1)
					//->filterDim(3, 3, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4d/pool"})
					->outputs({"inception_4d/pool_proj"})
					//->prevLayerIndices({54})
					//->nextLayerIndices({56})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(56)
					->name("inception_4d/output")
					->inputs({"inception_4d/1x1", "inception_4d/3x3", "inception_4d/5x5", "inception_4d/pool_proj"})
					->outputs({"inception_4d/output"})
					//->prevLayerIndices({49, 51, 53, 55})
					//->nextLayerIndices({57, 58, 60, 62})
					)

			//INCEPTION 4E
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(57)
					->name("inception_4e/1x1")
					->filterDim(1, 1, 528, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4d/output"})
					->outputs({"inception_4e/1x1"})
					//->prevLayerIndices({56})
					//->nextLayerIndices({64})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(58)
					->name("inception_4e/3x3_reduce")
					->filterDim(1, 1, 528, 160, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4d/output"})
					->outputs({"inception_4e/3x3_reduce"})
					//->prevLayerIndices({56})
					//->nextLayerIndices({59})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(59)
					->name("inception_4e/3x3")
					->filterDim(3, 3, 160, 320, 1)
					//->filterDim(3, 3, 96, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4e/3x3_reduce"})
					->outputs({"inception_4e/3x3"})
					//->prevLayerIndices({58})
					//->nextLayerIndices({64})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(60)
					->name("inception_4e/5x5_reduce")
					->filterDim(3, 3, 528, 32, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4d/output"})
					->outputs({"inception_4e/5x5_reduce"})
					//->prevLayerIndices({56})
					//->nextLayerIndices({61})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(61)
					->name("inception_4e/5x5")
					->filterDim(3, 3, 32, 128, 1)
					//->filterDim(3, 3, 16, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4e/5x5_reduce"})
					->outputs({"inception_4e/5x5"})
					//->prevLayerIndices({60})
					//->nextLayerIndices({64})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(62)
					->name("inception_4e/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"inception_4d/output"})
					->outputs({"inception_4e/pool"})
					//->prevLayerIndices({56})
					//->nextLayerIndices({63})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(63)
					->name("inception_4e/pool_proj")
					->filterDim(1, 1, 528, 128, 1)
					//->filterDim(3, 3, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_4e/pool"})
					->outputs({"inception_4e/pool_proj"})
					//->prevLayerIndices({62})
					//->nextLayerIndices({64})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(64)
					->name("inception_4e/output")
					->inputs({"inception_4e/1x1", "inception_4e/3x3",
								"inception_4e/5x5", "inception_4e/pool_proj"})
					->outputs({"inception_4e/output"})
					//->prevLayerIndices({57, 59, 61, 63})
					//->nextLayerIndices({65})
					)







			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(65)
					->name("pool4/3x3_s2")
					->poolDim(3, 3, 2)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"inception_4e/output"})
					->outputs({"pool4/3x3_s2"})
					//->prevLayerIndices({64})
					//->nextLayerIndices({66, 67, 69, 71})
					)

			//INCEPTION 5A
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(66)
					->name("inception_5a/1x1")
					->filterDim(1, 1, 832, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool4/3x3_s2"})
					->outputs({"inception_5a/1x1"})
					//->prevLayerIndices({65})
					//->nextLayerIndices({73})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(67)
					->name("inception_5a/3x3_reduce")
					->filterDim(1, 1, 832, 160, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool4/3x3_s2"})
					->outputs({"inception_5a/3x3_reduce"})
					//->prevLayerIndices({65})
					//->nextLayerIndices({68})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(68)
					->name("inception_5a/3x3")
					->filterDim(3, 3, 160, 320, 1)
					//->filterDim(3, 3, 96, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5a/3x3_reduce"})
					->outputs({"inception_5a/3x3"})
					//->prevLayerIndices({67})
					//->nextLayerIndices({73})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(69)
					->name("inception_5a/5x5_reduce")
					->filterDim(3, 3, 832, 32, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"pool4/3x3_s2"})
					->outputs({"inception_5a/5x5_reduce"})
					//->prevLayerIndices({65})
					//->nextLayerIndices({70})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(70)
					->name("inception_5a/5x5")
					->filterDim(3, 3, 32, 128, 1)
					//->filterDim(3, 3, 16, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5a/5x5_reduce"})
					->outputs({"inception_5a/5x5"})
					//->prevLayerIndices({69})
					//->nextLayerIndices({73})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(71)
					->name("inception_5a/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"pool4/3x3_s2"})
					->outputs({"inception_5a/pool"})
					//->prevLayerIndices({65})
					//->nextLayerIndices({72})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(72)
					->name("inception_5a/pool_proj")
					->filterDim(1, 1, 832, 128, 1)
					//->filterDim(3, 3, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5a/pool"})
					->outputs({"inception_5a/pool_proj"})
					//->prevLayerIndices({71})
					//->nextLayerIndices({73})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(73)
					->name("inception_5a/output")
					->inputs({"inception_5a/1x1", "inception_5a/3x3",
								"inception_5a/5x5", "inception_5a/pool_proj"})
					->outputs({"inception_5a/output"})
					//->prevLayerIndices({66, 68, 70, 72})
					//->nextLayerIndices({74, 75, 77, 79})
					)



			//INCEPTION 5B
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(74)
					->name("inception_5b/1x1")
					->filterDim(1, 1, 832, 384, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5a/output"})
					->outputs({"inception_5b/1x1"})
					//->prevLayerIndices({73})
					//->nextLayerIndices({81})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(75)
					->name("inception_5b/3x3_reduce")
					->filterDim(1, 1, 832, 192, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.09)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5a/output"})
					->outputs({"inception_5b/3x3_reduce"})
					//->prevLayerIndices({73})
					//->nextLayerIndices({76})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(76)
					->name("inception_5b/3x3")
					->filterDim(3, 3, 192, 384, 1)
					//->filterDim(3, 3, 96, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.03)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5b/3x3_reduce"})
					->outputs({"inception_5b/3x3"})
					//->prevLayerIndices({75})
					//->nextLayerIndices({81})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(77)
					->name("inception_5b/5x5_reduce")
					->filterDim(3, 3, 832, 48, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5a/output"})
					->outputs({"inception_5b/5x5_reduce"})
					//->prevLayerIndices({73})
					//->nextLayerIndices({78})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(78)
					->name("inception_5b/5x5")
					->filterDim(3, 3, 48, 128, 1)
					//->filterDim(3, 3, 16, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5b/5x5_reduce"})
					->outputs({"inception_5b/5x5"})
					//->prevLayerIndices({77})
					//->nextLayerIndices({81})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(79)
					->name("inception_5b/pool")
					->poolDim(3, 3, 1)
					->poolingType(Pooling<Dtype>::Max)
					->inputs({"inception_5a/output"})
					->outputs({"inception_5b/pool"})
					//->prevLayerIndices({73})
					//->nextLayerIndices({80})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(80)
					->name("inception_5b/pool_proj")
					->filterDim(1, 1, 832, 128, 1)
					//->filterDim(3, 3, 192, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					->inputs({"inception_5b/pool"})
					->outputs({"inception_5b/pool_proj"})
					//->prevLayerIndices({79})
					//->nextLayerIndices({81})
					)
			->layer((new typename DepthConcatLayer<Dtype>::Builder())
					->id(81)
					->name("inception_5b/output")
					->inputs({"inception_5b/1x1", "inception_5b/3x3",
								"inception_5b/5x5", "inception_5b/pool_proj"})
					->outputs({"inception_5b/output"})
					//->prevLayerIndices({74, 76, 78, 80})
					//->nextLayerIndices({82})
					)


			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(82)
					->name("pool5/7x7_s1")
					->poolDim(7, 7, 4)
					->poolingType(Pooling<Dtype>::Avg)
					->inputs({"inception_5b/output"})
					->outputs({"pool5/7x7_s1"})
					//->prevLayerIndices({81})
					//->nextLayerIndices({83})
					)

			->layer((new typename SoftmaxLayer<Dtype>::Builder())
					->id(83)
					->name("softmax")
					->nOut(1000)
					->pDropout(0.4)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					->biasFiller(ParamFillerType::Constant, 0.0)
					->inputs({"pool5/7x7_s1", "label"})
					->outputs({"prob"})
					//->prevLayerIndices({82})
					)
			->build();

	return layersConfig;
}




template <typename Dtype>
LayersConfig<Dtype>* createVGG19NetLayersConfig() {
	const float weight_const = 0.01f;
	const float bias_const = 0.1f;

    std::cout << std::endl;
	LayersConfig<Dtype>* layersConfig =
			(new typename LayersConfig<Dtype>::Builder())
			->layer((new typename InputLayer<Dtype>::Builder())
					->id(0)
					->name("input")
					//->nextLayerIndices({1})
					)

			// 1
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(1)
					->name("conv1_1")
					->filterDim(3, 3, 3, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({0})
					//->nextLayerIndices({2})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(2)
					->name("conv1_2")
					->filterDim(3, 3, 64, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({1})
					//->nextLayerIndices({3})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(3)
					->name("pool1")
					->poolDim(2, 2, 2)
					->poolingType(Pooling<Dtype>::Max)
					//->prevLayerIndices({2})
					//->nextLayerIndices({4})
					)

			// 2
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(4)
					->name("conv2_1")
					->filterDim(3, 3, 64, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({3})
					//->nextLayerIndices({5})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(5)
					->name("conv2_2")
					->filterDim(3, 3, 128, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({4})
					//->nextLayerIndices({6})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(6)
					->name("pool2")
					->poolDim(2, 2, 2)
					->poolingType(Pooling<Dtype>::Max)
					//->prevLayerIndices({5})
					//->nextLayerIndices({7})
					)


			// 3
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(7)
					->name("conv3_1")
					->filterDim(3, 3, 128, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({6})
					//->nextLayerIndices({8})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(8)
					->name("conv3_2")
					->filterDim(3, 3, 256, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({7})
					//->nextLayerIndices({9})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(9)
					->name("conv3_3")
					->filterDim(3, 3, 256, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({8})
					//->nextLayerIndices({10})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(10)
					->name("conv3_4")
					->filterDim(3, 3, 256, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({9})
					//->nextLayerIndices({11})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(11)
					->name("pool3")
					->poolDim(2, 2, 2)
					->poolingType(Pooling<Dtype>::Max)
					//->prevLayerIndices({10})
					//->nextLayerIndices({12})
					)


			// 4
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(12)
					->name("conv4_1")
					->filterDim(3, 3, 256, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({11})
					//->nextLayerIndices({13})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(13)
					->name("conv4_2")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({12})
					//->nextLayerIndices({14})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(14)
					->name("conv4_3")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({13})
					//->nextLayerIndices({15})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(15)
					->name("conv4_4")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({14})
					//->nextLayerIndices({16})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(16)
					->name("pool4")
					->poolDim(2, 2, 2)
					->poolingType(Pooling<Dtype>::Max)
					//->prevLayerIndices({15})
					//->nextLayerIndices({17})
					)


			// 5
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(17)
					->name("conv5_1")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({16})
					//->nextLayerIndices({18})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(18)
					->name("conv5_2")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({17})
					//->nextLayerIndices({19})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(19)
					->name("conv5_3")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({18})
					//->nextLayerIndices({20})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(20)
					->name("conv5_4")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({19})
					//->nextLayerIndices({21})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(21)
					->name("pool5")
					->poolDim(2, 2, 2)
					->poolingType(Pooling<Dtype>::Max)
					//->prevLayerIndices({20})
					//->nextLayerIndices({22})
					)


			// FC
			->layer((new typename FullyConnectedLayer<Dtype>::Builder())
					->id(22)
					->name("fc6")
					->nOut(4096)
					->pDropout(0.5)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::Type::ReLU)
					//->prevLayerIndices({21})
					//->nextLayerIndices({23})
					)
			->layer((new typename FullyConnectedLayer<Dtype>::Builder())
					->id(23)
					->name("fc7")
					->nOut(4096)
					->pDropout(0.5)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::Type::ReLU)
					//->prevLayerIndices({22})
					//->nextLayerIndices({24})
					)
			->layer((new typename SoftmaxLayer<Dtype>::Builder())
					->id(24)
					->name("softmaxLayer")
					->nOut(1000)
					->pDropout(0.0)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, 0.05)
					->biasFiller(ParamFillerType::Constant, 0.0)
					//->prevLayerIndices({23})
					)
			->build();

	return layersConfig;
}



template <typename Dtype>
LayersConfig<Dtype>* createVGG19NetLayersArtisticConfig() {
	const float weight_const = 0.01f;
		const float bias_const = 0.1f;
		const uint32_t poolKernel = 2;

        std::cout << std::endl;
		LayersConfig<Dtype>* layersConfig =
			(new typename LayersConfig<Dtype>::Builder())
			->layer((new typename InputLayer<Dtype>::Builder())
					->id(0)
					->name("input")
					//->nextLayerIndices({1})
					)

			// 1
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(1)
					->name("conv1_1")
					->filterDim(3, 3, 3, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({0})
					//->nextLayerIndices({2})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(2)
					->name("conv1_2")
					->filterDim(3, 3, 64, 64, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({1})
					//->nextLayerIndices({3})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(3)
					->name("pool1")
					->poolDim(poolKernel, poolKernel, 2)
					->poolingType(Pooling<Dtype>::Avg)
					//->prevLayerIndices({2})
					//->nextLayerIndices({4})
					)

			// 2
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(4)
					->name("conv2_1")
					->filterDim(3, 3, 64, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({3})
					//->nextLayerIndices({5})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(5)
					->name("conv2_2")
					->filterDim(3, 3, 128, 128, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({4})
					//->nextLayerIndices({6})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(6)
					->name("pool2")
					->poolDim(poolKernel, poolKernel, 2)
					->poolingType(Pooling<Dtype>::Avg)
					//->prevLayerIndices({5})
					//->nextLayerIndices({7})
					)


			// 3
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(7)
					->name("conv3_1")
					->filterDim(3, 3, 128, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({6})
					//->nextLayerIndices({8})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(8)
					->name("conv3_2")
					->filterDim(3, 3, 256, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({7})
					//->nextLayerIndices({9})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(9)
					->name("conv3_3")
					->filterDim(3, 3, 256, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({8})
					//->nextLayerIndices({10})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(10)
					->name("conv3_4")
					->filterDim(3, 3, 256, 256, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({9})
					//->nextLayerIndices({11})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(11)
					->name("pool3")
					->poolDim(poolKernel, poolKernel, 2)
					->poolingType(Pooling<Dtype>::Avg)
					//->prevLayerIndices({10})
					//->nextLayerIndices({12})
					)


			// 4
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(12)
					->name("conv4_1")
					->filterDim(3, 3, 256, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({11})
					//->nextLayerIndices({13})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(13)
					->name("conv4_2")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({12})
					//->nextLayerIndices({14})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(14)
					->name("conv4_3")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({13})
					//->nextLayerIndices({15})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(15)
					->name("conv4_4")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({14})
					//->nextLayerIndices({16})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(16)
					->name("pool4")
					->poolDim(poolKernel, poolKernel, 2)
					->poolingType(Pooling<Dtype>::Avg)
					//->prevLayerIndices({15})
					//->nextLayerIndices({17})
					)


			// 5
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(17)
					->name("conv5_1")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({16})
					//->nextLayerIndices({18})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(18)
					->name("conv5_2")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({17})
					//->nextLayerIndices({19})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(19)
					->name("conv5_3")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({18})
					//->nextLayerIndices({20})
					)
			->layer((new typename ConvLayer<Dtype>::Builder())
					->id(20)
					->name("conv5_4")
					->filterDim(3, 3, 512, 512, 1)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::ReLU)
					//->prevLayerIndices({19})
					//->nextLayerIndices({21})
					)
			->layer((new typename PoolingLayer<Dtype>::Builder())
					->id(21)
					->name("pool5")
					->poolDim(poolKernel, poolKernel, 2)
					->poolingType(Pooling<Dtype>::Avg)
					//->prevLayerIndices({20})
					//->nextLayerIndices({24})
					)


			// FC
					/*
			->layer((new typename FullyConnectedLayer<Dtype>::Builder())
					->id(22)
					->name("fc6")
					->nOut(4096)
					->pDropout(0.5)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::Type::ReLU)
					->prevLayerIndices({21})
					->nextLayerIndices({23}))
			->layer((new typename FullyConnectedLayer<Dtype>::Builder())
					->id(23)
					->name("fc7")
					->nOut(4096)
					->pDropout(0.5)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, weight_const)
					->biasFiller(ParamFillerType::Constant, bias_const)
					->activationType(Activation<Dtype>::Type::ReLU)
					->prevLayerIndices({22})
					->nextLayerIndices({24}))
					*/
			->layer((new typename SoftmaxLayer<Dtype>::Builder())
					->id(24)
					->name("softmaxLayer")
					->nOut(1)
					->pDropout(0.0)
					->weightUpdateParam(1, 1)
					->biasUpdateParam(2, 0)
					->weightFiller(ParamFillerType::Xavier, 0.1)
					//->weightFiller(ParamFillerType::Constant, weight_const)
					//->weightFiller(ParamFillerType::Gaussian, 0.05)
					->biasFiller(ParamFillerType::Constant, 0.0)
					//->prevLayerIndices({21})
					)
			->build();

	return layersConfig;
}




#endif /* DEBUG_H_ */
